#!/bin/sh

BRANCH_NAME=$(git symbolic-ref --short HEAD)

BRANCH_IN_COMMIT=0
if [ -f "$1" ]; then
  BRANCH_IN_COMMIT=$(grep -c "\[${BRANCH_NAME}\]" "$1")
fi

if [ -n "${BRANCH_NAME}" ] && [ "${BRANCH_IN_COMMIT}" -lt 1 ]; then
  if [ -f "$1" ]; then
    ESCAPED_BRANCH_NAME=$(printf '%s' "${BRANCH_NAME}" | sed 's/\//\\\//g')
    sed -i.bak -e "1s@^@[${ESCAPED_BRANCH_NAME}]: @" "$1"
  else
    echo "[${BRANCH_NAME}] " > "$1"
  fi
fi

exit 0
