load("@rules_proto_grpc_grpc_gateway//:defs.bzl", "gateway_openapiv2_combined_compile", "gateway_openapiv2_compile")

gateway_openapiv2_compile(
    name = "v1_gateway_openapiv2",
    protos = ["//api/proto/pictago/v1:v1_proto"],
)

gateway_openapiv2_combined_compile(
    name = "openapiv2_combined",
    protos = ["//api/proto/pictago/v1:v1_proto"],
)
