load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "user_management",
    srcs = ["server.go"],
    importpath = "github.com/ai-slop-code/pictago/pkg/user_management",
    visibility = ["//visibility:public"],
    deps = [
        "//api/proto/pictago/v1:v1_grpc_gateway",
        "//internal/user",
        "//internal/utils",
    ],
)

go_test(
    name = "user_management_test",
    timeout = "short",
    srcs = ["server_test.go"],
    embed = [":user_management"],
    deps = [
        "//api/proto/pictago/v1:v1_grpc_gateway",
        "//internal/user",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
