load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "user_management",
    srcs = ["server.go"],
    importpath = "github.com/ai-slop-code/pictago/pkg/user_management",
    visibility = ["//visibility:public"],
    deps = [
        "//api/proto/pictago/v1:v1_grpc_gateway",
        "//internal/user",
    ],
)
