load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "config",
    srcs = ["config.go"],
    importpath = "github.com/ai-slop-code/pictago/internal/config",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/log",
        "//internal/utils",
        "@com_github_spf13_viper//:viper",
    ],
)
